.. include:: _format_auto_docs/ndx-ecg_namespace_description.inc

.. raw:: latex

    \clearpage \newpage

.. _hdmf-type-specifications:

Type Specifications
===================

.. _ndx-ecg.extensions.yaml:

ndx-ecg.extensions.yaml
-----------------------

.. include:: _format_auto_docs/CardiacSeries_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/ECG_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/HeartRate_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/AuxiliaryAnalysis_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/ECGChannelsGroup_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/ECGRecDevice_description.inc

.. raw:: latex

    \clearpage \newpage

