.. _data_type_hierarchy:

Type Hierarchy
--------------

* :ref:`Container <sec-Container>`

   * :ref:`DynamicTable <sec-DynamicTable>`
   * :ref:`NWBContainer <sec-NWBContainer>`

      * :ref:`Device <sec-Device>`

         * :ref:`ECGRecDevice <sec-ECGRecDevice>`
      * :ref:`ECGChannelsGroup <sec-ECGChannelsGroup>`
      * :ref:`NWBDataInterface <sec-NWBDataInterface>`

         * :ref:`AuxiliaryAnalysis <sec-AuxiliaryAnalysis>`
         * :ref:`ECG <sec-ECG>`
         * :ref:`HeartRate <sec-HeartRate>`
         * :ref:`TimeSeries <sec-TimeSeries>`

            * :ref:`CardiacSeries <sec-CardiacSeries>`
* :ref:`Data <sec-Data>`

   * :ref:`ElementIdentifiers <sec-ElementIdentifiers>`
   * :ref:`VectorData <sec-VectorData>`


