.. _hdmf-type-specification-sources:

Schema Sources
==============

.. include:: _format_auto_docs/ndx-ecg_namespace_source.inc
.. _ndx-ecg.extensions.yaml_src:

ndx-ecg.extensions.yaml
-----------------------

.. include:: _format_auto_docs/CardiacSeries_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/ECG_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/HeartRate_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/AuxiliaryAnalysis_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/ECGChannelsGroup_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/ECGRecDevice_source.inc

.. raw:: latex

    \clearpage \newpage

