Format Overview
===============

.. _hdmf-type-namespace-doc:

ndx-ecg
-------

- **Description:** This extension is developed to extend NWB data standards to incorporate ECG recordings.
- **Name:** ndx-ecg
- **Version:** 0.1.0
- **Authors:**
    - Hamidreza Alimohammadi ([AT]DefenseCircuitsLab)

- **Contacts:**
    - alimohammadi.hamidreza@gmail.com

- **Schema:**
    - **namespace:** core 
    - **neurodata_types:** ['TimeSeries', 'Device', 'NWBDataInterface', 'LabMetaData'] 
    - **namespace:** hdmf-common 
    - **neurodata_types:** ['DynamicTable', 'VectorData'] 
    - **source:** ndx-ecg.extensions.yaml 


.. only:: html 

    .. include:: _format_auto_docs/format_spec_type_hierarchy.inc

